import type { BuildPartDefinition, BuildPartId } from "./BuildingTypes";

const FLOOR_SUPPORTS: BuildPartId[] = ["floor_1x1", "stone_floor_1x1", "deck_floor_1x1"];
const WALL_SUPPORTS: BuildPartId[] = [
  "thin_wall",
  "stone_wall",
  "half_wall",
  "railing",
  "fence",
  "pillar",
  "stone_pillar",
  "short_post",
  "door",
  "stone_door",
  "window",
  "wide_window",
];

export const BUILD_PARTS: Record<BuildPartId, BuildPartDefinition> = {
  floor_1x1: {
    id: "floor_1x1",
    label: "나무 바닥",
    category: "floor",
    slotKind: "tile",
    icon: "▱",
    spriteKey: "build_floor_1x1",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: false,
    requiresSupport: false,
    allowedOn: "ground",
    placementCost: [{ itemId: "wood", quantity: 1 }],
  },

  stone_floor_1x1: {
    id: "stone_floor_1x1",
    label: "돌 바닥",
    category: "floor",
    slotKind: "tile",
    icon: "▰",
    spriteKey: "build_stone_floor_1x1",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: false,
    requiresSupport: false,
    allowedOn: "ground",
    placementCost: [{ itemId: "stone", quantity: 2 }],
  },

  deck_floor_1x1: {
    id: "deck_floor_1x1",
    label: "데크 바닥",
    category: "floor",
    slotKind: "tile",
    icon: "▤",
    spriteKey: "build_deck_floor_1x1",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: false,
    requiresSupport: false,
    allowedOn: "ground",
    placementCost: [{ itemId: "wood", quantity: 2 }],
  },

  thin_wall: {
    id: "thin_wall",
    label: "나무 벽",
    category: "wall",
    slotKind: "edge",
    icon: "▌",
    spriteKey: "build_thin_wall",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: FLOOR_SUPPORTS,
    placementCost: [{ itemId: "wood", quantity: 2 }],
  },

  stone_wall: {
    id: "stone_wall",
    label: "돌 벽",
    category: "wall",
    slotKind: "edge",
    icon: "▥",
    spriteKey: "build_stone_wall",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: FLOOR_SUPPORTS,
    placementCost: [{ itemId: "stone", quantity: 3 }],
  },

  half_wall: {
    id: "half_wall",
    label: "반벽",
    category: "wall",
    slotKind: "edge",
    icon: "▂",
    spriteKey: "build_half_wall",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: FLOOR_SUPPORTS,
    placementCost: [{ itemId: "wood", quantity: 1 }],
  },

  railing: {
    id: "railing",
    label: "난간",
    category: "wall",
    slotKind: "edge",
    icon: "╫",
    spriteKey: "build_railing",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: FLOOR_SUPPORTS,
    placementCost: [{ itemId: "wood", quantity: 1 }],
  },

  fence: {
    id: "fence",
    label: "울타리",
    category: "wall",
    slotKind: "edge",
    icon: "♯",
    spriteKey: "build_fence",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: FLOOR_SUPPORTS,
    placementCost: [{ itemId: "wood", quantity: 1 }],
  },

  roof_1x1: {
    id: "roof_1x1",
    label: "나무 지붕",
    category: "roof",
    slotKind: "tile",
    icon: "⌂",
    spriteKey: "build_roof_1x1",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: WALL_SUPPORTS,
    placementCost: [
      { itemId: "wood", quantity: 2 },
      { itemId: "stone", quantity: 1 },
    ],
  },

  flat_roof_1x1: {
    id: "flat_roof_1x1",
    label: "평지붕",
    category: "roof",
    slotKind: "tile",
    icon: "▔",
    spriteKey: "build_flat_roof_1x1",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: WALL_SUPPORTS,
    placementCost: [{ itemId: "wood", quantity: 2 }],
  },

  thatch_roof_1x1: {
    id: "thatch_roof_1x1",
    label: "초가지붕",
    category: "roof",
    slotKind: "tile",
    icon: "⌃",
    spriteKey: "build_thatch_roof_1x1",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: WALL_SUPPORTS,
    placementCost: [{ itemId: "wood", quantity: 1 }],
  },

  pillar: {
    id: "pillar",
    label: "나무 기둥",
    category: "support",
    slotKind: "corner",
    icon: "▮",
    spriteKey: "build_pillar",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: [...FLOOR_SUPPORTS, "pillar", "stone_pillar", "short_post"],
    placementCost: [{ itemId: "wood", quantity: 2 }],
  },

  stone_pillar: {
    id: "stone_pillar",
    label: "돌 기둥",
    category: "support",
    slotKind: "corner",
    icon: "▯",
    spriteKey: "build_stone_pillar",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: [...FLOOR_SUPPORTS, "pillar", "stone_pillar", "short_post"],
    placementCost: [{ itemId: "stone", quantity: 2 }],
  },

  short_post: {
    id: "short_post",
    label: "짧은 말뚝",
    category: "support",
    slotKind: "corner",
    icon: "▪",
    spriteKey: "build_short_post",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: FLOOR_SUPPORTS,
    placementCost: [{ itemId: "wood", quantity: 1 }],
  },

  door: {
    id: "door",
    label: "나무 문",
    category: "door",
    slotKind: "edge",
    icon: "▯",
    spriteKey: "build_door",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: FLOOR_SUPPORTS,
    placementCost: [{ itemId: "wood", quantity: 2 }],
  },

  stone_door: {
    id: "stone_door",
    label: "돌문",
    category: "door",
    slotKind: "edge",
    icon: "▢",
    spriteKey: "build_stone_door",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: FLOOR_SUPPORTS,
    placementCost: [
      { itemId: "wood", quantity: 1 },
      { itemId: "stone", quantity: 2 },
    ],
  },

  window: {
    id: "window",
    label: "창문",
    category: "window",
    slotKind: "edge",
    icon: "▣",
    spriteKey: "build_window",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: FLOOR_SUPPORTS,
    placementCost: [
      { itemId: "wood", quantity: 1 },
      { itemId: "stone", quantity: 1 },
    ],
  },

  wide_window: {
    id: "wide_window",
    label: "넓은 창문",
    category: "window",
    slotKind: "edge",
    icon: "▦",
    spriteKey: "build_wide_window",
    size: { w: 1, d: 1, h: 1 },
    anchor: { x: 0.5, y: 1 },
    blocksMovement: true,
    requiresSupport: true,
    allowedOn: FLOOR_SUPPORTS,
    placementCost: [
      { itemId: "wood", quantity: 2 },
      { itemId: "stone", quantity: 1 },
    ],
  },
};

export const BUILD_PART_LIST = Object.values(BUILD_PARTS);

export function getBuildPartDefinition(partId: BuildPartId): BuildPartDefinition {
  return BUILD_PARTS[partId];
}
